# Generated by Django 2.2.7 on 2020-10-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20201027_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Establecimiento_Producto',
        ),
    ]
