# Generated by Django 2.2.7 on 2020-10-29 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_delete_establecimiento_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento_Producto',
            fields=[
                ('id_estabxprod', models.AutoField(primary_key=True, serialize=False)),
                ('stock_disponible', models.IntegerField()),
                ('stock_despacho', models.IntegerField()),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
    ]
