# Generated by Django 2.2.7 on 2020-11-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20201107_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=' ', upload_to=''),
        ),
        migrations.AlterField(
            model_name='politica',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
