# Generated by Django 2.2.7 on 2020-11-07 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20201107_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politica',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
