# Generated by Django 2.2.7 on 2020-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20201107_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politica',
            name='detalle',
            field=models.TextField(),
        ),
    ]
