# Generated by Django 2.2.7 on 2020-11-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20201108_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='combo', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tipo_Notificacion',
        ),
    ]
