# Generated by Django 2.2.7 on 2020-12-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20201110_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
    ]
