# Generated by Django 2.2.7 on 2020-12-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='precioAntes',
            field=models.FloatField(default=0.0),
        ),
    ]
