# Generated by Django 2.2.7 on 2020-12-04 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_oferta_precioantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='total',
            new_name='precio_total',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id_combo',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='id_establecimiento',
        ),
        migrations.RemoveField(
            model_name='detalle_carrito',
            name='precio',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_despachada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='tiene_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='tiene_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Carrito_Oferta',
            fields=[
                ('id_carritoxoferta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_oferta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Oferta')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito_Combo',
            fields=[
                ('id_carritoxcombo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_combo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Combo')),
            ],
        ),
    ]
