# Generated by Django 2.2.7 on 2020-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_auto_20201204_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_carrito',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detalle_carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
