# Generated by Django 2.2.7 on 2020-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_auto_20201205_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='precio_total',
            field=models.FloatField(default=0),
        ),
    ]
