# Generated by Django 2.2.7 on 2020-12-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_auto_20201206_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_combo',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carrito_oferta',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='carrito_combo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
