# Generated by Django 2.2.7 on 2020-12-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_auto_20201208_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
