# Generated by Django 2.2.7 on 2021-01-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_cupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='imagen',
            new_name='image',
        ),
    ]
