# Generated by Django 2.2.7 on 2021-01-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_auto_20210124_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='image',
            new_name='imagen',
        ),
    ]
