# Generated by Django 2.2.7 on 2021-01-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_auto_20210124_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cupon',
            old_name='image',
            new_name='imagen',
        ),
        migrations.CreateModel(
            name='Cupones',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('estado', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
    ]
