# Generated by Django 2.2.7 on 2021-01-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_auto_20210124_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupones',
            name='id_establecimiento',
        ),
        migrations.AddField(
            model_name='cupones',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Categoria'),
        ),
        migrations.AlterField(
            model_name='cupones',
            name='estado',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='Cupons',
            fields=[
                ('id_cupon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('estado', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
    ]
