# Generated by Django 2.2.7 on 2021-01-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_auto_20210124_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupons',
        ),
    ]
