# Generated by Django 2.2.7 on 2021-01-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_delete_cupons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupones',
        ),
    ]
