# Generated by Django 2.2.7 on 2021-01-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_delete_cupones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
