# Generated by Django 2.2.7 on 2021-01-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_cupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
