# Generated by Django 2.2.7 on 2021-01-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0036_notificacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Cupones',
            fields=[
                ('id_carritoxcupones', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('id_carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Carrito')),
                ('id_cupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones')),
            ],
        ),
    ]
