# Generated by Django 2.2.7 on 2021-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0037_carrito_cupones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupones',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
