# Generated by Django 2.2.7 on 2021-02-01 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0038_cupones_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaEnvio',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=300)),
                ('envio', models.FloatField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('tipo_entrega', models.CharField(default='Domicilio', max_length=100)),
                ('tipo_pago', models.CharField(default='Efectivo', max_length=100)),
                ('subtotal', models.FloatField()),
                ('envio', models.FloatField()),
                ('iva', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('observacion', models.CharField(max_length=400)),
                ('estado', models.CharField(choices=[('Espera', 'Espera'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('Devuelto', 'Devuelto')], default='Espera', max_length=10)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('iva', models.FloatField()),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
    ]
