# Generated by Django 2.2.7 on 2021-02-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0043_auto_20210219_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPedido',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('transaccion', models.IntegerField(max_length=100)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPedido',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=5)),
                ('justificacion', models.CharField(max_length=500)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
            ],
        ),
    ]
