# Generated by Django 2.2.7 on 2021-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0045_auto_20210219_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Recibido', 'Recibido'), ('Devuelto', 'Devuelto'), ('Anulado', 'Anulado')], default='Recibido', max_length=10),
        ),
    ]
