# Generated by Django 2.2.7 on 2021-03-28 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0047_auto_20210322_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
