# Generated by Django 2.2.7 on 2021-03-28 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0048_auto_20210328_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 3, 3, 1, 191696, tzinfo=utc)),
        ),
    ]
