# Generated by Django 2.2.7 on 2021-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0050_auto_20210328_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='combo',
            name='estado',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='cupones',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
