# Generated by Django 2.2.7 on 2021-04-02 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0051_auto_20210329_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(default='administrador', max_length=150)),
                ('cedula', models.CharField(max_length=10)),
                ('foto', models.ImageField(default=' ', upload_to='')),
                ('direccion', models.CharField(default='NONE', max_length=100)),
                ('fecha_Nac', models.DateField(default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
