# Generated by Django 2.2.7 on 2021-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0053_auto_20210402_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
    ]
