# Generated by Django 2.2.7 on 2022-09-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0058_producto_stock_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento_ZonaEnvio',
            fields=[
                ('id_estabxzona', models.AutoField(primary_key=True, serialize=False)),
                ('id_establecimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento')),
                ('id_zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.ZonaEnvio')),
            ],
        ),
    ]
