# Generated by Django 2.2.7 on 2022-09-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0060_codigo_codigo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id_sorteo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('numGanadores', models.IntegerField(default=0)),
                ('maxGanadores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sorteo_Usuario',
            fields=[
                ('id_sorteoxusuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_sorteo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Sorteo')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
    ]
