# Generated by Django 2.2.7 on 2022-09-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0061_sorteo_sorteo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_Monto',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Producto_Usuario',
            fields=[
                ('id_tarjetaxusuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Producto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta_Montoo_Usuario',
            fields=[
                ('id_tarjetaxusuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarjeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Tarjeta_Monto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Usuario')),
            ],
        ),
    ]
