# Generated by Django 2.2.7 on 2022-09-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0062_tarjeta_monto_tarjeta_montoo_usuario_tarjeta_producto_tarjeta_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='image',
            field=models.ImageField(default='ARTE_VARIEDAD_DE_PRODUCTOS.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
