# Generated by Django 2.2.7 on 2022-09-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0063_sorteo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='tipo',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
