# Generated by Django 2.2.7 on 2022-09-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0064_codigo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Producto',
            fields=[
                ('id_codigoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigoproducto', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField(default=1)),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Codigo_Monto',
            fields=[
                ('id_codigomonto', models.AutoField(primary_key=True, serialize=False)),
                ('codigomonto', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
            ],
        ),
    ]
