# Generated by Django 2.2.7 on 2022-09-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0065_codigo_monto_codigo_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarjeta_Montoo_Usuario',
            new_name='Tarjeta_Monto_Usuario',
        ),
    ]
