# Generated by Django 2.2.7 on 2022-09-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0066_auto_20220921_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codigo',
            name='id_establecimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Establecimiento'),
        ),
        migrations.AddField(
            model_name='codigo',
            name='image',
            field=models.ImageField(default='cabuto2_1_GZ6pJgk.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codigo',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='codigo_usuario',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
