# Generated by Django 2.2.7 on 2022-09-21 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0067_auto_20220921_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Cliente',
            fields=[
                ('id_codxcliente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cliente')),
                ('id_codigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Codigo')),
            ],
        ),
        migrations.DeleteModel(
            name='Codigo_Usuario',
        ),
    ]
