# Generated by Django 2.2.7 on 2022-09-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0069_cupones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='id_cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Cupones'),
        ),
    ]
