# Generated by Django 2.2.7 on 2022-09-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0070_codigo_id_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupones',
            name='tipo',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
