# Generated by Django 2.2.7 on 2022-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0072_cupones_monto_cupones_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id_repartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=120)),
                ('token', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor_Pedido',
            fields=[
                ('id_repedido', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Pedido')),
                ('id_repartidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.Repartidor')),
            ],
        ),
    ]
